### ISSUE TITLE
Add option to sign in with social media accounts also.

### ISSUE THREAD

**Issue by msk4862** [msk4862/WhatUp#6]
**Task**:  Currently, It only have email/password based login, We can add login option using social media accounts too.

**Comment by yoBoyio** [comment]
Hello @msk4862  I would like to work on this one.

**Comment by EnechukwuChibuike** [comment]
Can I do that?

**Comment by msk4862** [comment]
@yoBoyio go ahead!

**Comment by msk4862** [comment]
Track your progress here @yoBoyio

**Comment by msk4862** [comment]
@yoBoyio  you can also implement just signin with Google option for now.

**Comment by yoBoyio** [comment]
@msk4862 

> @yoBoyio you can also implement just signin with Google option for now.
> Or any one of the social account.

im working on google and facebook both .
