### ISSUE TITLE
Restyle circular loader, open for suggestions/discussion.

### ISSUE THREAD

**Issue by msk4862** [msk4862/WhatUp#7]
**Task**: Currently loader is taking whole screen. Maybe we can avoid that and restyle it.

**Comment by hendaoui** [comment]
Assign it to me :)

**Comment by tusharmaharana** [comment]
we could add a progress loader when we transition from page to page and for the login we could show the loader(with its height and width removed) in a wrapper div

**Comment by msk4862** [comment]
@tusharmaharana for now maybe we could just show the improved circular loader only for all pages.

**Comment by msk4862** [comment]
@tusharmaharana I'm assigning it to you, but please try to do it by tomorrow. Otherwise I've to assign to someone else.

**Comment by msk4862** [comment]
Track your progress here @tusharmaharana

**Comment by tusharmaharana** [comment]
> @tusharmaharana I'm assigning it to you, but please try to do it by tomorrow. Otherwise I've to assign to someone else.

alright, will try to do it by tomorrow

**Comment by msk4862** [comment]
@tusharmaharana  any progress on this?

**Comment by msk4862** [comment]
@tusharmaharana ??

**Comment by tusharmaharana** [comment]
@msk4862 sorry for the delay, I am already done and working on sending the PR now.
If you want we can either discuss it here or you can just see the PR for changes

**Comment by msk4862** [comment]
@tusharmaharana  yes, create a PR with a demo.

**Comment by tusharmaharana** [comment]
@msk4862 what do you mean by a demo, can you elaborate?

**Comment by msk4862** [comment]
@tusharmaharana by demo I mean a small video or screenshot (of loader in this case) to demonstrate your changes.
